// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFAqvDJxn3sVEQ01CHEpYRS9K1_-I_HJs',
    appId: '11:547841833460:android:ceff38b6b6d5438da9e1a1',
    messagingSenderId: '547841833460',
    projectId: 'kt-telematic-solutions',
    authDomain: 'fathima-hospial.firebaseapp.com',
    storageBucket: 'kt-telematic-solutions.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfGaIv_T8VReGeXZkoj9gWblT19GpP-OI',
    appId: '1:411671297625:android:fe311c862ac740a99fbb48',
    messagingSenderId: '411671297625',
    projectId: 'fathima-hospial',
    storageBucket: 'fathima-hospial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXDloeSf4sUNzMXd8lWRRO6ZcflwFjJd8',
    appId: '1:411671297625:ios:d5758b8a7ec0f0f89fbb48',
    messagingSenderId: '411671297625',
    projectId: 'fathima-hospial',
    storageBucket: 'fathima-hospial.appspot.com',
    iosClientId:
        '411671297625-5lh4m6p9g4fqnom6e3cuig9ajtgao6c5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXDloeSf4sUNzMXd8lWRRO6ZcflwFjJd8',
    appId: '1:411671297625:ios:a751883868fea13c9fbb48',
    messagingSenderId: '411671297625',
    projectId: 'fathima-hospial',
    storageBucket: 'fathima-hospial.appspot.com',
    iosClientId:
        '411671297625-5n510qrb8vkmha16smtf00qgq2pg8rn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
